### ISSUE TITLE
Incongruenze tra specifiche e file yaml

### ISSUE THREAD

**Issue by MBossiniB** [INPS-it/WaaS.Comuni#12]
Buongiorno,
abbiamo notato delle incongruenze tra quanto scritto nel documento di specifiche (INPS_WaaS-SIUSS-SpecificaTecnica_v1.0.1) e nello yaml waas_api_pal.yaml. Le riporto di seguito:

1. I nomi delle proprietà delle entry sono differenti. Ad esempio: nel pdf c'è flusso_content, mentre nello yaml è indicato come flusso.
2. La proprietà codice_beneficiario è presente nel pdf, ma non nello yaml. Questo punto è molto importante per capire se ad ogni entry debba essere associato un solo beneficiario con una sola prestazione oppure molteplici beneficiari con molteplici prestazioni.
3. La descrizione dell'id_flusso non è coerente nella documentazione: infatti nella decription per il progressivo giornaliero vengono indicati 7 caratteri (NNNNNNN), mentre nell'esempio e nel pattern 6.
```
id_flusso:

          description: >-
            Protocollo di identificazione del flusso. L'identificativo ha la seguente struttura: 'EEEEE.FMT.INPS.AAAAMMGG.NNNNNNN', dove:
            - EEEEE è il codice dell'ente erogatore
            - TIPO il formato utilizzato (es. SINBA o PS)
            - AAAAMMGG è la data di creazione del flusso
            - NNNNNNN è un progressivo giornaliero
          type: string
          example: "H501.PS.INPS.20160423.115235"
          pattern: '^[A-Z][0-9]{3}\.[A-Z]{2}\.[A-Z]{4}\.[0-9]{8}\.[0-9]{6}$' 
```

Potreste indicarci quali siano le specifiche corrette?

Queste informazioni per noi sono fondamentali per procedere con gli sviluppi, vi ringrazio in anticipo.
Cordiali Saluti
Bossini Martina
